apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestionapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestionapi
  template:
    metadata:
      labels:
        app: ingestionapi
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: ingestionapi
          image: arthur1702/ingestionapi:latest
          env:
            - name: TZ
              value: "America/Sao_Paulo"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
